import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UsersProvider } from "./users/user-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Users Listing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UsersProvider>
          <main className="flex flex-col items-center p-24">
            {children}
          </main>
        </UsersProvider>
      </body>
    </html>
  );
}
